### ISSUE TITLE
customCriteria closure has no aliases

### ISSUE THREAD

**Issue by EvertEt** [tadodotcom/grails-quick-search#10]
If I try to use the customCriteria:
```groovy
def customCriteria = { println it }
```
It prints an empty list: []

Is this a bug or am I using it wrong?

All code:
```groovy
def searchParams = [sort: 'firstName', order: 'asc', max: MAX_SEARCH_RESULT, offset: offset * MAX_SEARCH_RESULT]
def searchProperties = [firstName: "firstName", lastName: "lastName"]
def customCriteria = { println it }
PagedResultList userList = (PagedResultList) quickSearchService.search(domainClass: User, searchParams: searchParams, searchProperties: searchProperties, query: query, customCriteria: customCriteria)
```

In a debugging attempt we found that the code is always going into this if: https://github.com/tadodotcom/grails-quick-search/blob/master/grails-app/services/org/grails/plugins/quickSearch/QuickSearchService.groovy#L186

Thanks for your help!

**Comment by macrosak** [comment]
I am not sure what exactly do you want to achieve.

Custom criteria can help you if you want to restrict the search scope. The closure is added to the Grails Hibernate Criteria Builder.

An example for your use case:

```groovy
def customCriteria =  { eq('firstname', 'John') }
```

**Comment by EvertEt** [comment]
Thanks for your help. I did not know we had to use criteria's instead of checking the it itself.
Using eq this works. Thanks a lot!
